### PR TITLE
Port NetHack Sokoban 

### PR DESCRIPTION
**Pull request by BartekCupial**
### Introduction
I have added 8 Sokoban levels to the MiniHack based on the dat file from [NLE](https://github.com/facebookresearch/nle). These levels are challenging and have solutions available in the [NetHack Wiki](https://nethackwiki.com/wiki/Sokoban), making them useful for research on combining external knowledge to learn strategies for NetHack.

### Changes to Original NetHack Sokoban Levels
- All "wholes" have been changed into pits.
- Falling into a pit results in the agent's death.
- There are no monsters or items in any of the levels, including 4a and 4b Sokoban levels, which normally spawn a zoo filled with monsters.
- All doors are closed, but none are locked.

### Reward shaping and termination
The environment is completed when all pits are filled and the agent steps on the stairs down.
The agent receives a +1 reward for finishing the episode and a +0.1 reward for filling each pit.

### CODE REVIEW

**Comment by samvelyan** [comment]
Hi @BartekCupial. Many thanks for this wonderful PR. Could you please sign the Facebook CLA above so that we can proceed?

**Comment by BartekCupial** [comment]
I've already done it. Not sure why it is not checked.

**Comment by BartekCupial** [comment]
@samvelyan CLA is signed now, but I see that there is a test on macos that failed. I don't have access to this kind of hardware. Can you help?

**Comment by samvelyan** [comment]
Tests pass now. Thank you very much for your contribution @BartekCupial

**Pull request merged**
