### PR TITLE
Added an additional parameter for including alignment in blstats

### PR DESCRIPTION
**Pull request by samvelyan**
Added an additional parameter to MiniHack environments for including alignment flag in blstats.

This is to ensure that models trained on earlier MiniHack versions can be executed following NLE 0.9.0 update.

### CODE REVIEW

**Comment by samvelyan** [comment]
Example usage

```python
>>> import gym, minihack
>>> env = gym.make("MiniHack-River-v0", include_alignment_blstats=True)
>>> o = env.reset()
>>> len(o['blstats'])
27
>>> o['blstats']
array([38, 13, 16, 16, 16, 12, 15,  8,  8,  0, 12, 12,  1,  0,  2,  2,  7,
        0,  1,  0,  1,  1,  0,  0,  1,  0, -1])
>>> env.close()
>>> env = gym.make("MiniHack-River-v0", include_alignment_blstats=False)
>>> o = env.reset()
>>> len(o['blstats'])
26
>>> o['blstats']
array([32, 10, 10, 10, 18, 14, 12, 10, 11,  0, 12, 12,  1,  0,  2,  2,  7,
        0,  1,  0,  1,  1,  0,  0,  1,  0])
```

**Comment by SharathRaparthy** [comment]
This looks convenient now @samvelyan. Thank you.

**Comment by SharathRaparthy** [comment]
Hey @samvelyan ! Looks like `include_alignment_blstats` flag is not reflected in `env.observation_space`. Please see the following example - 
```
>>> import minihack
>>> import gym
>>> env = gym.make("MiniHack-MultiRoom-N6-v0", include_alignment_blstats=False)
>>> env.observation_space
Dict(blstats:Box(27,), chars:Box(21, 79), chars_crop:Box(9, 9), colors:Box(21, 79), colors_crop:Box(9, 9), glyphs:Box(21, 79), glyphs_crop:Box(9, 9), message:Box(256,), specials:Box(21, 79), specials_crop:Box(9, 9))
>>> env = gym.make("MiniHack-MultiRoom-N6-v0", include_alignment_blstats=True)
>>> env.observation_space
Dict(blstats:Box(27,), chars:Box(21, 79), chars_crop:Box(9, 9), colors:Box(21, 79), colors_crop:Box(9, 9), glyphs:Box(21, 79), glyphs_crop:Box(9, 9), message:Box(256,), specials:Box(21, 79), specials_crop:Box(9, 9))
```

**Comment by samvelyan** [comment]
Thanks @SharathRaparthy for pointing this out. https://github.com/facebookresearch/minihack/pull/85 resolves this.

**Comment by SharathRaparthy** [comment]
Great! Thanks @samvelyan

**Pull request merged**
